### ISSUE TITLE
Release the actual application code

### ISSUE THREAD

**Issue by meejah** [abopengov/contact-tracing-Android#1]
As per the terms of the GPL, you are required to release the code for the actual Android application that is released on Google Play to anyone who has downloaded that app.

This repository does not contain that code.

**Comment by thaipt** [comment]
This is the source code for this app on Google Play: https://play.google.com/store/apps/details?id=ca.albertahealthservices.contacttracing. 

I hope this will answer your question.

**Comment by meejah** [comment]
No it isn't; the code here has a different namespace than in that application (which uses `ca.albertahealthservices.*` and not `com.example.tracetogether.*` like in this repo: https://github.com/abopengov/contact-tracing-Android/tree/master/app/src/main/java/com/example/tracetogether)

**Comment by meejah** [comment]
https://github.com/abopengov/contact-tracing-Android/blob/d80cd5ac3325183435e41951b73d7fba5e116c3b/app/src/release/assets/mfpclient.properties#L2

**Comment by gkozens** [comment]
The source code for the application has been released, however any components considered sensitive and specific to Alberta Health has been removed. Here is a list of the differences:

•	All licensed artwork has been replace with the transparent images that are of the same resolution
•	Changed package names
•	Renamed files, variables, and references specific to Alberta Health
•	Replaced font with an open source font
•	Removed mfp certificate file in assets and commented out code that pins said certificate
•	Removed all references to server names
•	Replaced sample config and build file in README.md file to be more generic

The Readme file contains a list of the above changes.

**Comment by meejah** [comment]
So are you trying to say that this repository is that code, or is it somewhere else?

Obviously I'm not a lawyer, but the GPL doesn't work like that; you can't just not-release some of your application code -- you need to release the very code that's running the APK that is in Google Play.

I also can't see how a public certificate pin or any of the rest of that list is "sensitive" in any way. No matter, because you've already put it on a public server and so what even is the point of making those assets slightly less convenient to access?

**Comment by meejah** [comment]
e.g. `assets/mfpclient.properties` is easily recovered from Google Play:

```
wlServerProtocol=https
wlServerHost=mfp.secure.abtracetogether.ca
wlServerPort=443
wlServerContext=/mfp/
languagePreferences=en
```

...as are all the other assets and and missing `.properties` files and `mfpcertificate.cer`, which `openssl x509` can print nicely:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            01:e2:73:c7:ef:4e:0b:66:62:7c:59:49:c5:41:5a:8c
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: C = US, ST = CA, L = San Francisco, O = "CloudFlare, Inc.", CN = CloudFlare Inc ECC CA-2
        Validity
            Not Before: Apr 21 00:00:00 2020 GMT
            Not After : Oct  9 12:00:00 2020 GMT
        Subject: C = US, ST = CA, L = San Francisco, O = "Cloudflare, Inc.", CN = sni.cloudflaressl.com
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:67:74:aa:9f:09:28:f5:c4:64:71:fc:b3:da:8d:
                    ab:46:67:b4:3a:7d:2e:18:5e:01:bf:96:3c:8b:f6:
                    89:57:45:6c:e5:70:58:c5:b4:ec:3d:d8:7f:32:d4:
                    11:d9:6d:5d:af:8a:c0:dd:15:fb:95:2a:93:e1:1b:
                    ac:2b:e8:15:3e
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Authority Key Identifier: 
                keyid:3E:74:2D:1F:CF:45:75:04:7E:3F:C0:A2:87:3E:4C:43:83:51:13:C6

            X509v3 Subject Key Identifier: 
                FD:91:AC:4A:30:53:25:CC:15:F3:C8:15:A8:E9:F5:BB:5E:E2:BD:12
            X509v3 Subject Alternative Name: 
                DNS:secure.abtracetogether.ca, DNS:*.secure.abtracetogether.ca, DNS:sni.cloudflaressl.com
            X509v3 Key Usage: critical
                Digital Signature
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 CRL Distribution Points: 

                Full Name:
                  URI:http://crl3.digicert.com/CloudFlareIncECCCA2.crl

                Full Name:
                  URI:http://crl4.digicert.com/CloudFlareIncECCCA2.crl

            X509v3 Certificate Policies: 
                Policy: 2.16.840.1.114412.1.1
                  CPS: https://www.digicert.com/CPS
                Policy: 2.23.140.1.2.2

            Authority Information Access: 
                OCSP - URI:http://ocsp.digicert.com
                CA Issuers - URI:http://cacerts.digicert.com/CloudFlareIncECCCA-2.crt

            X509v3 Basic Constraints: critical
                CA:FALSE
            CT Precertificate SCTs: 
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : B2:1E:05:CC:8B:A2:CD:8A:20:4E:87:66:F9:2B:B9:8A:
                                25:20:67:6B:DA:FA:70:E7:B2:49:53:2D:EF:8B:90:5E
                    Timestamp : Apr 21 19:54:33.010 2020 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:44:02:20:03:6F:11:59:B9:8E:5E:B7:E4:B5:BA:84:
                                8C:42:D4:4D:C6:78:EC:AD:2B:1B:6A:10:8A:DB:48:44:
                                50:E7:3C:41:02:20:33:37:55:B9:7A:01:B1:9D:31:89:
                                16:FE:C3:F5:1A:FB:12:9E:A9:F5:2A:33:38:8D:8C:CD:
                                D5:52:FC:A0:02:04
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : F0:95:A4:59:F2:00:D1:82:40:10:2D:2F:93:88:8E:AD:
                                4B:FE:1D:47:E3:99:E1:D0:34:A6:B0:A8:AA:8E:B2:73
                    Timestamp : Apr 21 19:54:33.051 2020 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:46:02:21:00:90:11:69:6F:5E:CE:98:C5:D8:78:C2:
                                D2:07:78:BF:90:A3:11:AD:A3:A8:31:55:EC:F6:09:2D:
                                89:E0:7A:79:54:02:21:00:B8:26:2F:83:FA:F7:15:79:
                                E1:BD:F3:42:88:7C:B5:40:76:77:40:03:C5:E3:64:05:
                                3D:E5:2F:8C:7B:20:B2:3E
    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:e3:4e:93:77:e2:e1:13:a7:6d:80:0d:a1:cb:
         0d:4a:6d:85:e3:f1:6c:d2:1c:94:dd:fc:0d:34:92:d5:8b:60:
         66:02:21:00:c7:49:51:a2:58:83:fa:b3:38:69:14:a3:2c:81:
         04:c2:a9:df:4b:54:cc:d7:a5:05:72:b2:6e:34:d5:e2:47:45
```

...which, not surprisingly, is simply the certificate that every client gets every time it connects to `mfp.secure.abtracetogether.ca` (so, that's good, the pin is correct).

**Comment by gkozens** [comment]
The source code has been provided with a corresponding read.me file documenting the differences between the source code provided and the production application. The exclusions are environment specific components and the source code released is compliant with all requirements of the GPL 3.0 licencing agreement.

**Comment by meejah** [comment]
Looks like it was considered entertaining to change the "characteristic id" from BlueTrace/OpenTrace's value (and not release that). This is that value:

```
V2_CHARACTERISTIC_ID = "7bee419e-8882-11ea-bc55-0242ac130003"
BLE_SSID = "70f34cb2-8882-11ea-bc55-0242ac130003"
```

**Comment by AndASM** [comment]
How is this resolved?
https://www.gnu.org/licenses/gpl-faq.en.html#DistributingSourceIsInconvenient
https://www.gnu.org/licenses/gpl-faq.en.html#DistributeExtendedBinary

Why does this app have a unique interpretation of the license that differs from the explanation given by the organization that wrote the license?
